name: Dev - Build and Deploy to KIND
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and load dev image
        run: |
          docker build -t ticker_service:dev -f docker/Dockerfile .
          kind load docker-image ticker_service:dev
      - name: Deploy to KIND
        run: |
          kubectl apply -f kubernetes/ticker_service.yaml
